<a href="https://colab.research.google.com/github/Mustafa-AbdulRazek/NLP-Transformers/blob/master/000_pytorch_tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

In [2]:
data = [[1, 3], [3, 4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 3],
        [3, 4]])

In [3]:
np_arr = np.array(data)
x_np = torch.from_numpy(np_arr)
x_np

tensor([[1, 3],
        [3, 4]])

In [4]:
x_ones = torch.ones_like(x_data)
print(f"ones tensor: \n {x_ones} \n")

ones tensor: 
 tensor([[1, 1],
        [1, 1]]) 



In [6]:
x_rand = torch.rand_like(x_data, dtype=torch.float)
print(f"random tensor: \n {x_rand} \n")


random tensor: 
 tensor([[0.0034, 0.1787],
        [0.1935, 0.9244]]) 



In [7]:
shape = (2, 3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor= torch.zeros(shape)

print(f"{rand_tensor} \n {ones_tensor} \n {zeros_tensor} \n")

tensor([[0.6878, 0.3792, 0.3396],
        [0.1988, 0.5483, 0.7094]]) 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 
 tensor([[0., 0., 0.],
        [0., 0., 0.]]) 



In [8]:
# tensor Attributes: shape, dtype, device on which they are stored

tensor = torch.rand(3, 4)

print(f"{tensor.shape} \n {tensor.dtype} \n {tensor.device}")

torch.Size([3, 4]) 
 torch.float32 
 cpu


In [9]:
# tensor operations: transposing, indexing, slicing, math, linear alg, rand sampling

if torch.cuda.is_available():
    tensor = tensor.to('cuda')
    print(f"{tensor.device}")

In [10]:
# standard numpy like indexing and slicing

tensor = torch.ones(4, 4)
tensor[:, 1] = 0
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [13]:
# joining (concat) tensors

t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


In [15]:
# multiplying tensors
# element wise product
print(f"{tensor.mul(tensor)}\n{tensor * tensor}\n")

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])



In [16]:
# compute matrix multiplication btw 2 tensors

print(f"{tensor.matmul(tensor.T)}\n{tensor @ tensor.T}")

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])


In [17]:
# inplace operations
# operations that have _ suffix are in-place, eg. x.copy_(), x.t_()
# in-place ops save some memory.

print(tensor, "\n")
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


In [18]:
# Bridge with Numpy
# tensors and numpy arr can share their memory-locations on CPU, and changine one affect the other.

# tensor to numpy array

t = torch.ones(5)
print(f"{t}")

n = t.numpy()
print(f"{n}")

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


In [19]:
# change in one affect the other
t.add_(1)
print(t)
print(n)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [21]:
# array to tensor
n = np.ones(5)
t = torch.from_numpy(n)

# change in numpy affect the other
np.add(n, 1, out=n)
# t.add_(1) # same
print(t)
print(n)

tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
[2. 2. 2. 2. 2.]
